/* MIT — Math Dance, prepared for Wanmin Liu. */
'use strict';
const $=id=>document.getElementById(id);
const text={
sv:{full:'Helskärm',heading:'Rör er tillsammans.',lead:'Följ grafen med armarna och kroppen. Små rörelser eller sittande går också bra.',background:'Bakgrund',light:'Ljus',dark:'Mörk',duration:'Längd',twoMinutes:'2 minuter',threeMinutes:'3 minuter',level:'Innehåll',level1:'1 · Grundformer',level2:'2 · Fler former',level3:'3 · Fler funktioner',chooseFunctions:'Välj funktioner',constant:'Konstant',linear:'Linjär',quadratic:'Andragrad',absolute:'Absolutbelopp',cubic:'Tredjegrad',quartic:'Fjärdegrad · W',sin:'Sinus',cos:'Cosinus',tan:'Tangens',exp:'Exponential',log:'Logaritm',derivatives:'Derivataserie',accelerate:'Öka takten mot slutet',showFormula:'Visa formel',speech:'Engelsk röst',jumps:'Ibland från låg till hög position',volume:'Musikvolym',tempoNote:'120 BPM · vid acceleration: 8 → 6 → 4 slag per graf. Svårare former får mer tid. Fast avslutning de sista 10 sekunderna.',play:'Starta',pause:'Pausa',resume:'Fortsätt',replay:'Spela igen',reset:'Börja om',keys:'Mellanslag: pausa / fortsätt · F: helskärm · Esc: lämna helskärm',instructions:'Instruktioner',credits:'Ljud och material',finishedNote:'Slappna av och sänk armarna.',shape:'Forma grafen med kroppen',ready:'Redo',prepare:'Gör er redo',running:'Följ rytmen',paused:'Pausad',finished:'Klart!',final:'Sista 10 sekunderna',up:'Upp',down:'Ner',left:'Åt vänster',right:'Åt höger',low:'Låg position · böj knäna',high:'Hög position · håll armarna vågrätt',middle:'Till mitten',jump:'Res dig snabbt eller gör ett litet hopp',derivativeStart:'Startfunktion · fjärdegrad',differentiate:'Derivera',select:'Välj minst en funktion.',audioError:'Ljudet kunde inte starta. Försök igen i en aktuell webbläsare.',voiceUnavailable:'Ingen lokal engelsk röst hittades. Start och nedräkning visas på skärmen.',voiceReady:'Engelsk röst på enheten. Röst och talfördröjning kan variera.',loading:'Förbereder musiken…',derivativeNote:'Derivataserie',frozen:'Pausa eller börja om för att ändra inställningarna.'},
zh:{full:'全屏',heading:'一起跟着图像动起来',lead:'用手臂和身体比划图像。也可以坐着参与或做小幅度动作。',background:'背景',light:'浅色',dark:'深色',duration:'时长',twoMinutes:'2 分钟',threeMinutes:'3 分钟',level:'内容',level1:'1 · 基础图形',level2:'2 · 更多形状',level3:'3 · 更多函数',chooseFunctions:'选择函数类型',constant:'常数函数',linear:'一次函数',quadratic:'二次函数',absolute:'绝对值',cubic:'三次函数',quartic:'四次 · W 形',sin:'正弦',cos:'余弦',tan:'正切',exp:'指数',log:'对数',derivatives:'连续求导片段',accelerate:'后半程逐步加速',showFormula:'显示公式',speech:'英文语音',jumps:'偶尔从低位直接到高位',volume:'音乐音量',tempoNote:'120 BPM · 加速时每张 8 → 6 → 4 拍；复杂图形保留较长时间。最后 10 秒固定收尾。',play:'开始',pause:'暂停',resume:'继续',replay:'再来一次',reset:'重新开始',keys:'空格：暂停 / 继续 · F：全屏 · Esc：退出全屏',instructions:'使用说明',credits:'音频与素材说明',finishedNote:'放下手臂，放松。',shape:'用身体比划图像',ready:'就绪',prepare:'准备',running:'跟随节拍',paused:'已暂停',finished:'结束',final:'最后 10 秒',up:'向上',down:'向下',left:'向左',right:'向右',low:'低位 · 屈膝',high:'高位 · 水平举手',middle:'回到中位',jump:'快速起身，也可以轻轻跳起',derivativeStart:'起始函数 · 四次',differentiate:'求导',select:'请至少选择一种函数。',audioError:'无法启动音频，请使用新版浏览器重试。',voiceUnavailable:'未找到设备本地英语声音；仍显示开场和倒计时。',voiceReady:'使用设备英语语音；音色和播报延迟可能不同。',loading:'正在准备音乐…',derivativeNote:'连续求导片段',frozen:'暂停或重新开始后调整设置。'},
en:{full:'Fullscreen',heading:'Move together.',lead:'Follow the graph with your arms and body. Small or seated movements work too.',background:'Background',light:'Light',dark:'Dark',duration:'Duration',twoMinutes:'2 minutes',threeMinutes:'3 minutes',level:'Content',level1:'1 · Basic shapes',level2:'2 · More shapes',level3:'3 · More functions',chooseFunctions:'Choose functions',constant:'Constant',linear:'Linear',quadratic:'Quadratic',absolute:'Absolute value',cubic:'Cubic',quartic:'Quartic · W',sin:'Sine',cos:'Cosine',tan:'Tangent',exp:'Exponential',log:'Logarithmic',derivatives:'Derivative sequence',accelerate:'Speed up towards the end',showFormula:'Show formula',speech:'English voice',jumps:'Occasional low-to-high moves',volume:'Music volume',tempoNote:'120 BPM · with acceleration: 8 → 6 → 4 beats per graph. Complex shapes get more time. Fixed final 10 seconds.',play:'Start',pause:'Pause',resume:'Resume',replay:'Play again',reset:'Restart',keys:'Space: pause / resume · F: fullscreen · Esc: leave fullscreen',instructions:'Instructions',credits:'Audio and assets',finishedNote:'Lower your arms and relax.',shape:'Make the shape with your body',ready:'Ready',prepare:'Get ready',running:'Follow the beat',paused:'Paused',finished:'Finished',final:'Final 10 seconds',up:'Up',down:'Down',left:'Left',right:'Right',low:'Low position · bend your knees',high:'High position · arms horizontal',middle:'Back to the middle',jump:'Rise quickly or make a small jump',derivativeStart:'Starting function · quartic',differentiate:'Differentiate',select:'Choose at least one function.',audioError:'Audio could not start. Try again in a current browser.',voiceUnavailable:'No local English voice found. Opening and countdown remain visible.',voiceReady:'Uses your device’s English voice; sound and speech latency vary.',loading:'Preparing music…',derivativeNote:'Derivative sequence',frozen:'Pause or restart to change settings.'}
};
for(const [language,entries] of Object.entries({"zh": {"relations": "数学变化片段", "width": "观察开口宽窄", "narrow": "开口逐渐收窄", "same": "公式变了，图像不变 · 保持姿势", "flip": "上下翻转 · 观察开口方向", "vertex": "标出顶点与对称轴", "roots": "标出与 x 轴的交点", "rootsCloser": "两个零点逐渐靠近", "doubleRoot": "两个零点合为一个 · 与 x 轴相切", "fold": "把 x 轴下方的部分向上翻折", "wave": "用手臂比划波浪", "amplitude": "波浪变高 · 周期不变", "frequency": "波浪变密 · 振幅不变", "inverse": "沿虚线 y = x 镜像 · 坐标互换"}, "en": {"relations": "Transformation sequences", "width": "Notice the opening width", "narrow": "The opening gets narrower", "same": "New formula, same graph · hold your pose", "flip": "Flip vertically · notice the opening", "vertex": "Vertex and axis of symmetry", "roots": "Notice the x-intercepts", "rootsCloser": "The two roots move closer", "doubleRoot": "One double root · touching the x-axis", "fold": "Fold the part below the x-axis upwards", "wave": "Make a wave with your arms", "amplitude": "Taller waves · same period", "frequency": "More waves · same amplitude", "inverse": "Reflect across y = x · swap coordinates"}, "sv": {"relations": "Matematiska förändringar", "width": "Se öppningens bredd", "narrow": "Öppningen blir smalare", "same": "Ny formel, samma graf · håll positionen", "flip": "Vänd upp och ner · se öppningen", "vertex": "Toppunkt och symmetrilinje", "roots": "Se skärningarna med x-axeln", "rootsCloser": "Nollställena närmar sig varandra", "doubleRoot": "En dubbelrot · tangerar x-axeln", "fold": "Vik delen under x-axeln uppåt", "wave": "Forma en våg med armarna", "amplitude": "Högre vågor · samma period", "frequency": "Fler vågor · samma amplitud", "inverse": "Spegla i y = x · byt koordinater"}}))Object.assign(text[language],entries);
for(const [language,entries] of Object.entries({"zh": {"footwork": "脚步动作", "footworkNote": "默认：手臂动作，可坐着参与。开启：增加左右迈步、回位和轻屈膝。", "feetFinish": "双脚站稳 · 手臂回到中位", "feetReady": "原地站稳 · 用手臂保持图形", "stepRight": "向屏幕右侧小迈一步 · 保持手臂形状", "stepLeft": "向屏幕左侧小迈一步 · 保持手臂形状", "feetReturn": "迈回原位 · 保持手臂形状", "feetBend": "轻屈膝 · 手臂随图像下移", "feetStand": "站直回到原位 · 手臂随图像上移", "shape": "用手臂比划图像", "left": "手臂向左移", "right": "手臂向右移", "up": "手臂向上移", "down": "手臂向下移", "low": "手臂放低 · 保持水平", "high": "手臂抬高 · 保持水平", "middle": "手臂回到中位", "jumps": "允许偶尔轻轻跳起", "jump": "轻轻跳起，或站直并抬高手臂"}, "en": {"footwork": "Include footwork", "footworkNote": "Off: arm movements, seated or standing. On: more side steps, returns and gentle knee bends.", "feetFinish": "Feet steady · arms back to the middle", "feetReady": "Stand in place · hold the shape with your arms", "stepRight": "Small step to screen right · hold the arm shape", "stepLeft": "Small step to screen left · hold the arm shape", "feetReturn": "Step back to your starting place · hold the shape", "feetBend": "Bend your knees gently · lower the arm shape", "feetStand": "Stand upright again · raise the arm shape", "shape": "Make the shape with your arms", "left": "Move your arms left", "right": "Move your arms right", "up": "Move your arms up", "down": "Move your arms down", "low": "Arms low · hold them horizontal", "high": "Arms high · hold them horizontal", "middle": "Arms back to the middle", "jumps": "Allow occasional small jumps", "jump": "Small jump, or stand upright and raise your arms"}, "sv": {"footwork": "Ta med steg", "footworkNote": "Av: armrörelser, sittande eller stående. På: fler steg åt sidorna, tillbaka och lätta knäböj.", "feetFinish": "Stå stadigt · armarna tillbaka till mitten", "feetReady": "Stå på plats · forma grafen med armarna", "stepRight": "Ett litet steg åt höger på skärmen · behåll armformen", "stepLeft": "Ett litet steg åt vänster på skärmen · behåll armformen", "feetReturn": "Ta ett steg tillbaka till startplatsen · behåll formen", "feetBend": "Böj knäna lite · sänk armformen", "feetStand": "Stå rakt igen · höj armformen", "shape": "Forma grafen med armarna", "left": "Flytta armarna åt vänster", "right": "Flytta armarna åt höger", "up": "Flytta armarna uppåt", "down": "Flytta armarna neråt", "low": "Armarna lågt · håll dem vågrätt", "high": "Armarna högt · håll dem vågrätt", "middle": "Armarna tillbaka till mitten", "jumps": "Tillåt små hopp ibland", "jump": "Ett litet hopp, eller stå rakt och höj armarna"}}))Object.assign(text[language],entries);
let lang='sv',state='ready',ctx=null,gain=null,source=null,origin=0,pausedAt=0,frames=[],active=-1,voice=null,busy=false,spoken=new Set(),utterance=null;
let duration=120,current=window.MATH_GRAPHS.find(g=>g.id==='constant_1_0_0');
const planner=DanceSequence.createPlanner(window.MATH_GRAPHS,window.MATH_SCENES),buffers=new Map();
const tr=k=>text[lang][k]||k;
const enabledKinds=()=>[...document.querySelectorAll('#function-options input:checked')].map(e=>e.value);
function makeOptions(){const fragment=document.createDocumentFragment();for(const kind of Object.keys(DanceSequence.weights)){const label=document.createElement('label'),input=document.createElement('input'),span=document.createElement('span');input.type='checkbox';input.value=kind;input.checked=DanceSequence.presets[1].includes(kind);span.dataset.t=kind;span.textContent=tr(kind);label.append(input,span);fragment.append(label)}$('function-options').append(fragment)}
function makeGrid(){const ns='http://www.w3.org/2000/svg',g=$('grid');for(let n=-6;n<=6;n++){const p=400+n*60,line=document.createElementNS(ns,'path');line.setAttribute('d',`M${p} 40V760 M40 ${p}H760`);line.setAttribute('class',n===0?'axis':'grid');g.append(line);if(n&&Math.abs(n)<6){const a=document.createElementNS(ns,'text');a.setAttribute('x',p);a.setAttribute('y',424);a.setAttribute('text-anchor','middle');a.textContent=n;g.append(a);const b=document.createElementNS(ns,'text');b.setAttribute('x',384);b.setAttribute('y',400-n*60+6);b.setAttribute('text-anchor','end');b.textContent=n;g.append(b)}}}
function elapsed(){return state==='running'||state==='finished'?Math.max(0,ctx.currentTime-origin):pausedAt}
function cue(){if(current.kind==='derivative')return current.step===0?tr('derivativeStart'):`${tr('differentiate')} · ${current.step}/5`;return tr(frames[active]?.cue||'shape')}
function formula(){const show=$('formula-toggle').checked;$('formula').innerHTML=show?current.mathml:current.kind==='derivative'?current.notationMathml:'';$('graph-title').textContent=current.formula;$('movement').textContent=cue()}
function annotations(){
 const ns='http://www.w3.org/2000/svg';$('guides').replaceChildren();$('annotations').replaceChildren();
 const element=(tag,attrs,value)=>{const e=document.createElementNS(ns,tag);for(const [key,val] of Object.entries(attrs))e.setAttribute(key,val);if(value!==undefined)e.textContent=value;return e};
 if(current.guide){const g=current.guide;const d=g.type==='vertical'?`M${400+g.x*60} 40V760`:'M40 760L760 40';$('guides').append(element('path',{d,class:'reference-line'}));$('annotations').append(element('text',{x:g.type==='vertical'?412+g.x*60:660,y:g.type==='vertical'?68:120,class:'point-label'},g.type==='vertical'?`x = ${g.x}`:'y = x'))}
 for(const point of current.markers||[]){const x=400+point.x*60,y=400-point.y*60;$('annotations').append(element('circle',{cx:x,cy:y,r:6,class:'key-point'}),element('text',{x:x+12,y:y-14,class:'point-label'},`(${point.x}, ${point.y})`))}
}
function draw(index){active=index;current=planner.map.get(frames[index].graph);$('curve').setAttribute('d',current.path);annotations();formula();const count=Math.round((frames[index].end-frames[index].start)*2);$('beats').replaceChildren(...Array.from({length:count},()=>document.createElement('span')))}
function labels(){document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(e=>e.textContent=tr(e.dataset.t));$('play').textContent=tr(busy?'loading':state==='running'?'pause':state==='paused'?'resume':state==='finished'?'replay':'play');$('status').textContent=tr(state==='running'?(elapsed()<8?'prepare':elapsed()>=8+duration-10?'final':'running'):state);$('voice-info').textContent=tr(voice?'voiceReady':'voiceUnavailable');formula()}
function lock(value){document.querySelectorAll('#settings input,#settings select').forEach(e=>{if(!['volume','speech'].includes(e.id))e.disabled=value})}
function voices(){const choices=('speechSynthesis'in window?speechSynthesis.getVoices():[]).filter(v=>v.localService&&/^en[-_]/i.test(v.lang));const female=/Samantha|Victoria|Karen|Moira|Tessa|Fiona|Zira|Susan|Hazel|female/i;voice=choices.find(v=>female.test(v.name))||choices.find(v=>v.default)||choices[0]||null;labels()}
function say(phrase){if(!$('speech').checked||!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();utterance=new SpeechSynthesisUtterance(phrase);utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=1.05;utterance.volume=.95;utterance.pitch=1;speechSynthesis.speak(utterance)}
function cancelSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel()}
function speechAt(id,phrase){if(spoken.has(id))return;spoken.add(id);say(phrase)}
function refreshClock(left){const n=Math.max(0,Math.ceil(left));$('clock').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;$('clock').classList.toggle('urgent',n<=10);}
function reset(){if(busy)return;source?.stop();source=null;cancelSpeech();state='ready';pausedAt=0;frames=[];active=-1;spoken.clear();duration=Number($('duration').value);current=planner.get('constant');$('curve').setAttribute('d',current.path);annotations();$('intro').hidden=true;$('done').hidden=true;$('countdown').hidden=true;$('progress').style.width='0%';$('beats').replaceChildren();refreshClock(duration);lock(false);$('error').textContent='';$('jump-option').hidden=!$('footwork').checked;labels()}
async function start(){if(busy)return;if(state==='running'){pause();return}if(state==='paused'){await resume();return}if(!enabledKinds().length){$('error').textContent=tr('select');return}reset();busy=true;$('play').disabled=true;lock(true);labels();
try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();gain=gain||ctx.createGain();gain.disconnect();gain.connect(ctx.destination);gain.gain.value=Number($('volume').value)/100;
frames=planner.plan({duration,kinds:enabledKinds(),accelerate:$('accelerate').checked,derivatives:$('derivatives').checked,relations:$('relations').checked,footwork:$('footwork').checked,jumps:$('jumps').checked});
if(!buffers.has(duration)){const score=DanceMusic.render(duration);const b=ctx.createBuffer(1,score.data.length,score.sampleRate);b.copyToChannel(score.data,0);buffers.set(duration,b)}
source=ctx.createBufferSource();source.buffer=buffers.get(duration);source.connect(gain);origin=ctx.currentTime+.08;source.start(origin);state='running';pausedAt=0;spoken.clear();draw(0);$('intro').hidden=false;$('done').hidden=true;speechAt('welcome','Let’s do the math dance together!');
}catch(e){source?.stop();source=null;state='ready';lock(false);$('error').textContent=tr('audioError');console.error(e)}finally{busy=false;$('play').disabled=false;labels()}}
function pause(){if(state!=='running')return;pausedAt=elapsed();state='paused';ctx.suspend();cancelSpeech();$('announcement').textContent=tr('paused');labels()}
async function resume(){try{await ctx.resume();state='running';labels()}catch{$('error').textContent=tr('audioError')}}
function animate(){if(state==='running'){
 const p=elapsed(),time=p-8;
 if(p<8){$('intro').hidden=false;$('intro-line').textContent=p<3.3?'Let’s do the math dance together!':'Are you ready?';$('intro-number').textContent=p<5?'':String(8-Math.floor(p));if(p>=3.3&&p<5)speechAt('ready','Are you ready?');if(p>=5){const n=8-Math.floor(p);speechAt('intro'+n,['','One','Two','Three'][n])}refreshClock(duration)}
 else if(time>=duration){state='finished';$('intro').hidden=true;$('countdown').hidden=true;$('done').hidden=false;$('progress').style.width='100%';refreshClock(0);speechAt('done','Well done!');$('announcement').textContent='Well done!';lock(false);labels()}
 else{$('intro').hidden=true;if(time<.6)speechAt('go','Go!');const index=DanceSequence.frameAt(frames,time);if(index!==active)draw(index);const f=frames[index];const beat=Math.floor((time-f.start)*2);[...$('beats').children].forEach((e,i)=>e.classList.toggle('on',i<=beat));$('progress').style.width=((time-f.start)/(f.end-f.start)*100)+'%';refreshClock(duration-time);
 if(time>=duration-10){const n=Math.ceil(duration-time);$('countdown').hidden=false;$('countdown').textContent=n;const numbers=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten'];speechAt('end'+n,numbers[n]);$('status').textContent=tr('final')}else{$('status').textContent=tr('running');$('countdown').hidden=true}}
}requestAnimationFrame(animate)}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.body.classList.toggle('present')}}
makeOptions();makeGrid();reset();voices();if('speechSynthesis'in window)speechSynthesis.addEventListener('voiceschanged',voices);
$('play').addEventListener('click',start);$('reset').addEventListener('click',reset);$('fullscreen').addEventListener('click',fullscreen);$('language').addEventListener('change',()=>{lang=$('language').value;labels()});
document.querySelectorAll('input[name=theme]').forEach(e=>e.addEventListener('change',()=>{document.documentElement.dataset.theme=e.value}));
$('level').addEventListener('change',()=>{const level=Number($('level').value);document.querySelectorAll('#function-options input').forEach(e=>e.checked=DanceSequence.presets[level].includes(e.value));$('derivatives').checked=level>=2;reset()});
for(const id of ['duration','accelerate','derivatives','relations','footwork','jumps'])$(id).addEventListener('change',reset);
document.querySelectorAll('#function-options input').forEach(e=>e.addEventListener('change',reset));$('formula-toggle').addEventListener('change',formula);$('volume').addEventListener('input',()=>{if(gain)gain.gain.setTargetAtTime(Number($('volume').value)/100,ctx.currentTime,.04)});$('speech').addEventListener('change',()=>{if(!$('speech').checked)cancelSpeech()});
document.addEventListener('fullscreenchange',()=>document.body.classList.toggle('present',!!document.fullscreenElement));document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();start()}if(e.key.toLowerCase()==='f')fullscreen();if(e.key==='Escape')document.body.classList.remove('present')});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('pagehide',()=>{cancelSpeech();source?.stop()});
requestAnimationFrame(animate);
